version: '3'
services:
  node-app:
    build: ./NodeServer
    volumes:
      - ./uploads:/usr/src/uploads
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      
  
  flask-app:
    build: ./FlaskServer
    volumes:
      - ./uploads:/usr/src/uploads
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq

  react-app:
    build: ./ReactApp
    ports:
      - "3000:3000"
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ port for application communication
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
   
